### ISSUE TITLE
Too slow when loading inception model on windows server

### ISSUE THREAD

**Issue by elepherai** [GuYuc/WS-DAN.PyTorch#12]
Hi, after training, I tried to use eval.py to do evaluation.

Eval on my win10 PC works perfectly, but pretty slow on windows server.

After dubugging, I found that it takes about 20 minutes when loading inception model on windows server.

![image](https://user-images.githubusercontent.com/43477405/72679184-bcf12c80-3ae7-11ea-8651-764275e63437.png)

**Comment by GuYuc** [comment]
@elepherai Hi. Thank you for posting a problem here. Actually all my experiments were done on an ubuntu based server, and no model-loading problems occurred on my platform. I suggest you to post the problem to other community for help, because it seems more like a system problem or pytorch problem on windows server.

**Comment by elepherai** [comment]
Thanks~

**Comment by hturki** [comment]
To chime in here - are you sure that this is not due to https://discuss.pytorch.org/t/loading-inceptionv3-taking-a-lot-of-time/68067?

**Comment by elepherai** [comment]
> To chime in here - are you sure that this is not due to https://discuss.pytorch.org/t/loading-inceptionv3-taking-a-lot-of-time/68067?

Downgrade scipy to 1.3.3 works. Thank you.

pip install --upgrade scipy==1.3.3
